version: '3.7'

services:
  opensuse-leap-tests:
    image: local/cobbler-test-opensuse-leap
    build:
      context: .
      dockerfile: docker/rpms/opensuse_Leap_153/openSUSE_Leap.dockerfile
    container_name: cobbler-test-openSUSE-Leap

  centos8-build:
    image: local/cobbler-centos8
    container_name: cobbler-centos8
    build:
      context: .
      dockerfile: docker/rpms/CentOS_8/CentOS8.dockerfile
    volumes:
      - ./rpm-build/el8:/usr/src/cobbler/rpm-build

  fedora33-build:
    image: local/cobbler-fedora33
    container_name: cobbler-fedora33
    build:
      context: .
      dockerfile: docker/rpms/Fedora_34/Fedora34.dockerfile
    volumes:
      - ./rpm-build/f33:/usr/src/cobbler/rpm-build
