name: Building Cobbler packages

on:
  push:
    branches: [main, release*]
    tags:
      - "v*"
  pull_request:
    branches: [main, release*]

jobs:
  build-rockylinux9-rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build a Rocky Linux 9 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh rl9 docker/rpms/Rocky_Linux_9/Rocky_Linux_9.dockerfile
      - name: Archive RPMs
        uses: actions/upload-artifact@v4
        with:
          name: rpms-rockylinux-9
          path: |
            rpm-build/RPMS/*.rpm
  build-fedora41-rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build a Fedora 41 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh fc41 docker/rpms/Fedora_41/Fedora41.dockerfile
      - name: Archive RPMs
        uses: actions/upload-artifact@v4
        with:
          name: rpms-fedora-37
          path: |
            rpm-build/RPMS/*.rpm
  build-opensuse-leap-rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System dependencies
        run: sudo apt-get install -y rename
      - name: Build a openSUSE Leap 15 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh opensuse-leap docker/rpms/opensuse_leap/openSUSE_Leap15.dockerfile
      - name: Rename RPM
        run: |
          sudo file-rename -v -d -e 's/(^cobbler.*)-(\d+\.\d+\.\d+)-1\.(\w+)\.rpm/$1-$2-1.leap.$3.rpm/' rpm-build/RPMS/*.rpm
      - name: Archive RPMs
        uses: actions/upload-artifact@v4
        with:
          name: rpms-opensuse-leap
          path: |
            rpm-build/RPMS/*.rpm
  build-opensuse-tumbleweed-rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System dependencies
        run: sudo apt-get install -y rename
      - name: Build a openSUSE Tumbleweed Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh opensuse-tumbleweed docker/rpms/opensuse_tumbleweed/openSUSE_TW.dockerfile
      - name: Rename RPM
        run: |
          sudo file-rename -v -d -e 's/(^cobbler.*)-(\d+\.\d+\.\d+)-1\.(\w+)\.rpm/$1-$2-1.tw.$3.rpm/' rpm-build/RPMS/*.rpm
      - name: Archive RPMs
        uses: actions/upload-artifact@v4
        with:
          name: rpms-opensuse-tumbleweed
          path: |
            rpm-build/RPMS/*.rpm
  build-debian11-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System dependencies
        run: sudo apt-get install -y rename
      - name: Build a Debian 11 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb11 docker/debs/Debian_11/Debian11.dockerfile
      - name: Rename DEB
        run: |
          sudo file-rename -v -d -e 's/(^cobbler.*)_(\d+\.\d+\.\d+)_all\.deb/$1_$2_all.deb11.deb/' deb-build/*.deb
      - name: Archive DEBs
        uses: actions/upload-artifact@v4
        with:
          name: debs-debian11
          path: |
            deb-build/*.deb
  build-debian12-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install System dependencies
        run: sudo apt-get install -y rename
      - name: Build a Debian 12 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb12 docker/debs/Debian_12/Debian12.dockerfile
      - name: Rename DEB
        run: |
          sudo file-rename -v -d -e 's/(^cobbler.*)_(\d+\.\d+\.\d+)_all\.deb/$1_$2_all.deb12.deb/' deb-build/*.deb
      - name: Archive DEBs
        uses: actions/upload-artifact@v4
        with:
          name: debs-debian12
          path: |
            deb-build/*.deb
  build-wheel:
    name: Build Python Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mark directory as safe for Git
        run: git config --global --add safe.directory /__w/cobbler/cobbler
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: "**/setup.py"
          python-version: ">=3.6"
      - name: Update apt cache
        run: >-
          sudo apt-get update
      - name: Install system dependencies
        run: >-
          sudo apt-get install -y
          tar
          make
          libsasl2-dev
          libldap2-dev
          libssl-dev
          libsystemd-dev
          tree
      - name: Install dependencies
        run: pip3 install .[docs]
      # Creating the release tarball executes the clean target
      - name: Build the source tarball
        run: make release
      - name: Build the wheel
        run: make build
      - name: Show tree
        run: tree
      - name: Archive Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: |
            build/cobbler-*.whl
            release/cobbler-*.tar.gz
  create-release:
    name: Build the release and create a GitHub release
    runs-on: ubuntu-latest
    needs:
      [
        build-rockylinux9-rpms,
        build-fedora41-rpms,
        build-opensuse-leap-rpms,
        build-opensuse-tumbleweed-rpms,
        build-debian11-debs,
        build-debian12-debs,
        build-wheel,
      ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: Download all built artifacts
        with:
          path: artifacts
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Cobbler ${{ env.RELEASE_VERSION }}
          discussion_category_name: "Announcements"
          files: |
            artifacts/debs-debian11/*.deb
            artifacts/debs-debian12/*.deb
            artifacts/rpms-fedora-37/*.rpm
            artifacts/rpms-opensuse-leap/*.rpm
            artifacts/rpms-opensuse-tumbleweed/*.rpm
            artifacts/rpms-rockylinux-9/*.rpm
            artifacts/wheel/release/*.tar.gz
            artifacts/wheel/build/*.whl
          body_path: changelog/${{ env.RELEASE_VERSION }}.md
