name: Benchmark Report generation

on:
  workflow_dispatch:
    inputs:
      rounds:
        description: "The number of rounds for the benchmark"
        required: true
        type: number

jobs:
  run_performance_tests:
    name: Run Performance Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v4
      - name: Replace number of rounds in the test setup class
        run: sed -i '/[[:space:]]\{4\}test_rounds = 1/s/.$/'${{ inputs.rounds }}'/g' tests/performance/__init__.py
      - name: Pull Docker Test Container
        run: docker pull registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Run previously built Docker Container
        run: docker run --privileged -t -d -v $PWD:/code --name cobbler registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Trust the git repository inside the container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "git config --global --add safe.directory /code"
      - name: Setup Cobbler in the Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "./docker/develop/scripts/setup-supervisor.sh"
      - name: Run the Performance Tests inside the Docker Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "pytest --benchmark-only --benchmark-autosave tests/performance"
      - name: Stop and remove the container
        run: docker stop cobbler && docker rm cobbler
      # https://github.com/actions/upload-artifact
      - name: Upload benchmark report to GH artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: .benchmarks/
          if-no-files-found: error
