name: Testing Cobbler

on:
  push:
    branches:
      - master
      - release30
      - release32
  pull_request:
    branches:
      - master
      - release30
      - release32

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker Test Container
        run: docker pull registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:latest
      - name: Run previously built Docker Container
        run: docker run --cap-add=NET_ADMIN -t -d -v $PWD:/code --name cobbler registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:latest
      - name: Setup Cobbler in the Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "./docker/develop/scripts/setup-supervisor.sh"
      - name: Run the Tests inside the Docker Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "pytest --cov=./cobbler && codecov --token=1064928c-6477-41be-9ac2-7ce5e6d1fd8b --commit=${GITHUB_SHA}"
      - name: Stop and remove the container
        run: docker stop cobbler && docker rm cobbler
