name: Testing Cobbler

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    name: "Unit-Tests"
    steps:
      - uses: actions/checkout@v4
      - name: Pull Docker Test Container
        run: docker pull registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Run previously built Docker Container
        run: docker run --privileged -t -d -v $PWD:/code --name cobbler registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Setup Cobbler in the Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "./docker/develop/scripts/setup-supervisor.sh"
      - name: Run the Tests inside the Docker Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "pytest --cov=./cobbler --benchmark-skip && git config --global --add safe.directory /code && coverage xml && codecov --token=1064928c-6477-41be-9ac2-7ce5e6d1fd8b --commit=${GITHUB_SHA}"
      - name: Stop and remove the container
        run: docker stop cobbler && docker rm cobbler
      # https://github.com/actions/upload-artifact
      - name: Upload coverage report to GH artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error
  integration-tests:
    runs-on: ubuntu-latest
    name: "Integration-Tests - ${{ matrix.test }}"
    strategy:
      fail-fast: false
      matrix:
        test: [basic, import-debian, import-freebsd, import-redhat, import-suse, import-ubuntu, import-vmware, import-xen, settings-cli, svc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull Docker Test Container
        run: docker pull registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Run previously built Docker Container
        run: docker run --privileged -t -d -v $PWD:/code --name cobbler registry.opensuse.org/systemsmanagement/cobbler/github-ci/containers/cobbler-test-github:main
      - name: Setup Cobbler in the Container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "./docker/develop/scripts/setup-supervisor.sh"
      - name: Run the import tests inside the Docker container
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec -u 0 -it cobbler bash -c "make SYSTESTS='${{ matrix.test }}-*' system-test"
      - name: Stop and remove the container
        run: docker stop cobbler && docker rm cobbler
